blank_issues_enabled: false
contact_links:
  - name: 📃 Documentation
    url: https://github.com/rabilrbl/jiotv_go/blob/main/README.md#table-of-contents
    about: Don't know how or where to start? Check out our documentation!
  - name: 🗨 Telegram Support Group
    url: https://telegram.me/jiotv_go_chat
    about: Got a question? Need help? Join our Telegram support group!
  - name: 🗨 GitHub Discussions
    url: https://github.com/rabilrbl/jiotv_go/discussions
    about: Got something you think should change or be added? Search for or start a new discussion!